# Generated by Django 2.1.7 on 2019-04-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kicker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('guest_player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_player_1', to='kicker.Player')),
                ('guest_player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_player_2', to='kicker.Player')),
                ('home_player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_player_1', to='kicker.Player')),
                ('home_player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_player_2', to='kicker.Player')),
            ],
        ),
    ]
