# Generated by Django 2.1.7 on 2019-04-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicker', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guest_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
